name: Main Flow Android EX

on: [push]

jobs:
  build-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build assemble
        run: ./gradlew assemble

  unit-test:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        run: ./gradlew test

  check-lint:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Lint
        run: ./gradlew lint

  check-klint:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Klint
        run: ./gradlew ktlintVerification
      - name: Upload klint result
        uses: actions/upload-artifact@v2
        with:
          name: ktlint-result
          path: ${{ github.workspace }}/app/build/reports/ktlint/ktlint-checkstyle.xml

  check-detekt:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Detekt
        run: ./gradlew detektVerification
      - name: Upload detekt result
        uses: actions/upload-artifact@v2
        with:
          name: detekt-result
          path: ${{ github.workspace }}/app/build/reports/detekt/detekt-checkstyle.xml

  danger:
    needs: [unit-test,check-klint,check-detekt]
    runs-on: ubuntu-latest
    steps:
      - name: Download detekt result
        uses: actions/download-artifact@v2
        with:
          name: detekt-result
      - name: Download klint result
        uses: actions/download-artifact@v2
        with:
          name: ktlint-result
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: test files
        run: ls
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: MeilCli/danger-action@v5
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_KEY }}