name: Main Flow Android EX

on: [push]

jobs:
  build-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build assemble
        run: ./gradlew assemble

  unit-test:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        run: ./gradlew test

  build-lint:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Lint
        run: ./gradlew lint

  build-klint:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Klint
        run: ./gradlew ktlintVerification