name: Main Flow Android EX

on: [push]

jobs:
  build-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build assemble
        run: ./gradlew assemble
      - name: Upload Apk
      - uses: actions/upload-artifact@v2
        with:
          name: App
          path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk

  unit-test:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        run: ls ${{ github.workspace }}/app/build/outputs/apk/

  build-lint:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Lint
        run: ./gradlew lint