name: Main Flow Android EX

on: [push]

jobs:
  build-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build assemble
        run: ./gradlew assemble

  unit-test:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        run: ./gradlew test

  check-lint:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Lint
        run: ./gradlew lint

  check-klint:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Klint
        run: ./gradlew ktlintVerification
      - name: Upload klint result
        uses: actions/upload-artifact@v2
        with:
          name: ktlint-result
          path: ${{ github.workspace }}/app/build/reports/ktlint/ktlint-checkstyle.xml

  check-detekt:
    needs: [build-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Detekt
        run: ./gradlew detektVerification
      - name: Upload detekt result
        uses: actions/upload-artifact@v2
        with:
          name: detekt-result
          path: ${{ github.workspace }}/app/build/reports/detekt/detekt-checkstyle.xml